module.exports={
    ADMIN_COLLECTION:'admin',
    USER_COLLECTION:'user',
    CATEGORY_COLLECTION:'category',
    PRODUCT_COLLECTION:'product',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    WISHLIST_COLLECTION:'wishlist',
    WALLET_COLLECTION:'wallet',
    COUPON_COLLECTION:'coupon',
    BANNER_COLLECTION:'banner'
}